### ISSUE TITLE
Page: How to contribute

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#11]
First draft can contain wording from [proposal for the editorial processes](https://make.wordpress.org/core/2022/07/06/proposed-editorial-process-for-the-new-developer-blog/)

**Comment by bph** [comment]
Started on https://developer.wordpress.org/news/?page_id=179&preview=1&_ppp=7a13507f2a

**Comment by bph** [comment]
For now, it's ready for review: https://developer.wordpress.org/news/?page_id=179&preview=1&_ppp=6fab0c63a6

**Comment by justintadlock** [comment]
I've given it a couple of read-throughs.  Looks pretty good to me.  I have just a few minor notes.

Use the [Oxford comma](https://make.wordpress.org/docs/style-guide/punctuation/commas/) after "process":

> Be part of the editorial group, approve topics, organize meetings, shepherd blog posts through the process and assist with publishing posts.

Comma needed after "published":

> Ideas become tasks as posts to be written, peer-reviewed, published and amplified via social networks and subscription.

Use uppercase "D" for "discussions":

> In Progress – a writer has started working on the post. discussions are held in issue comments.

**Comment by mburridge** [comment]
_Apologies for all the comments. Feel free to disregard any that you don't agree with or where I might have misinterpreted your intention._

> You can contribute by review blog posts according to editorial guidelines or from a technical aspect.

You can contribute by reviewing blog posts according to the editorial guidelines, or from a technical point of view.

> Be part of the editorial group, approve topics, organize meetings, shepherd blog posts through the process and assist with publishing posts.

As part of the editorial group you would: approve topics, organize meetings, shepherd blog posts through the process and assist with publishing posts.

> Ideas become tasks as posts to be written, peer-reviewed, published and amplified via social networks and subscription.

_Not completely sure what you're saying here but my interpretation is:_
Ideas that are approved become tasks that result in posts which will need to be written, peer-reviewed, published and amplified via social networks and subscription.

> Ideas for new content can be posted to [Discussion > Ideas](https://github.com/WordPress/developer-blog-content/discussions/categories/ideas) for discussion. Often ideas, that are still being developed. These may need feedback and additional details before they are ready to be ready for approval and can be assigned to a writer.

Ideas for new content can be posted to [Discussion > Ideas](https://github.com/WordPress/developer-blog-content/discussions/categories/ideas) for further discussion. Usually these will be ideas for posts that still need further development or where the initial concept needs fleshing out. These ideas may need feedback and additional details before they are going to be ready for approval and can then be assigned to a writer.

> You can contribute by commenting and help flesh out a previously broad idea. Or contribute your idea, you would like to learn more about on the blog.

You can contribute by commenting in the discussions and help flesh out a previously broad idea. Alternatively you could suggest an idea of your own, perhaps something that you would like to learn more about on the blog.

> The issue would need the final summary of the future blog post, and a rough outline of the post.

Once turned into an issue it should have a summary of the future blog post, and a rough outline of the post.

> Once created, the issue will be labeled with flow labels that signal the progress through the publishing process.

Once created, the issue will be labeled with flow labels that indicate the stage of its progress through the publishing process.

> In Progress – a writer has started working on the post. discussions are held in issue comments.

In Progress – a writer has started working on the post. Once an idea has been turned into an issue further discussion is held in issue comments, rather than in the discussion that previously existed.

> The Status Table tab gives a fast overview of each post’s status.

The Status Table tab gives a quick overview of each post’s status.

**Comment by bph** [comment]
Thanks, @justintadlock and @mburridge for going over the page.

**Comment by bph** [comment]
This page is now published: [How to contribute](https://developer.wordpress.org/news/how-to-contribute/)
