### ISSUE TITLE
A tutorial about the highlights of the browser and focus modes of the Navigation Block

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#149]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/137

<div type='discussions-op-text'>

<sup>Originally posted by **tinjure20** June 23, 2023</sup>
Since my first contribution just got [published](https://developer.wordpress.org/news/2023/06/the-style-book-a-one-stop-shop-for-styling-block-themes/), I have begun playing around with a few new features that are anticipated to be included in the WordPress 6.3 release. 

There has been [significant progress](https://github.com/WordPress/gutenberg/issues/50396#issuecomment-1594836796) on the Navigation Block recently. I have been looking at a few features, such as browser mode ([#50396](https://github.com/WordPress/gutenberg/issues/50396)), focus mode ([#39286](https://github.com/WordPress/gutenberg/pull/39286)), and [related](https://github.com/WordPress/gutenberg/pull/51492) features of the Nav block. Even though I have not yet thoroughly researched all the related GitHub tickets, I wanted to put the idea out there early for discussion to see if it would be a good topic for a tutorial. 

The workflow will become more detailed as the Nav Block enters 6.3 Beta and its dev notes draft is available. If the topic is approved during the upcoming meeting and assigned to me, I hope to complete the first draft for review around the 6.3 release date.

**Resources**
- [Navigation on Browse Mode #50396 ](https://github.com/WordPress/gutenberg/issues/50396) 
- [Add focus mode for Navigation Menus #39286](https://github.com/WordPress/gutenberg/pull/39286)
- [Navigation on Browse Mode #50396](https://github.com/WordPress/gutenberg/issues/50396) 
- [Site Editor: Add Library for Template Parts & Patterns Management #51078 ](https://github.com/WordPress/gutenberg/pull/51078)
- [Navigation 6.3 Priorities](https://github.com/WordPress/gutenberg/issues/50165) 
-  [Dev Notes tracking issue for WordPress 6.3](https://github.com/WordPress/gutenberg/issues/51484) </div>

**Comment by bph** [comment]
The topic has been approved. The discussion is now locked,
Please continue the conversation on the issue
- #149

**Comment by bph** [comment]
Ganesh @tinjure20, the Editorial Group approved your topic suggestion. Please comment on this issue so it can be assigned to you.

**Comment by tinjure20** [comment]
@bph I totally agree with [@OGlekler](https://wordpress.slack.com/team/UHEG39DUG).  The Navigation block is the most complicated block, and so is the topic complicated. I suggested the topic not because I am an expert, but because I wanted to challenge myself to learn more and then share it with others. I am hoping for a lot of guidance/advice throughout the process. Also, I also fully agree with her suggestions regarding the title modification and limiting its scope to features that are only landing into 6.3.

**Comment by getdave** [comment]
I have made [a video covering a lot of changes to Navigation in WordPress 6.3](https://www.youtube.com/watch?v=s1L28GuA-y0) if that's helpful at all?

As one of the regular contributors to the Navigation aspect of the editor I'm also happy to help/advise here as required.

**Comment by tinjure20** [comment]
Hi @getdave. I've already watched your informative video a few times. Very helpful indeed! I appreciate your offer of help/advise, which I was already considering reaching out to you when my draft is ready to share.

I am still juggling other things, but I'm looking forward to putting my notes together, soon. I would like to consult with you before sharing the outline/draft with others. Would you mind if I contact you by Slack DM?

**Comment by getdave** [comment]
You are welcome and that is fine. Feel free to reach out. I do have some vacation coming up so (just in case) if you drop your questions in the [dedicated Core Slack channel for Navigation](https://wordpress.slack.com/archives/C01KDAZJMQ9) someone will be able to assist you 🙇

**Comment by bph** [comment]
Glad you two connected @getdave and @tinjure20 :-) 

Just be aware that the YouTube video can't be linked from the WordPress Developer Blog due to the external link policy for documentation that was adopted. 

Ganesh, please let me know how I can assist you getting started on your next blog post. I almost would suggest to wait until the documentation team finishes the End-User Documentation, but it seems they are looking for contributors to help with writing it.

[Call for volunteers to help with 6.3 end-user documentation](https://make.wordpress.org/docs/2023/07/18/call-for-volunteers-to-help-with-6-3-end-user-documentation/)

**Comment by getdave** [comment]
> Just be aware that the YouTube video can't be linked from the WordPress Developer Blog due to the external link policy for documentation that was adopted.

Interesting I didn't know that. I can reprise a variant for the Learn WP video site if that helps?

**Comment by tinjure20** [comment]
Thanks @bph for taking part in the discussion and your suggestions. 

> Just be aware that the YouTube video can't be linked from the WordPress Developer Blog due to the external link policy for documentation that was adopted.
> Ganesh, please let me know how I can assist you getting started on your next blog post.

I'm aware of Dev Blog citation policy. I was actually contemplating asking @getdave, how I could cite the details from his YouTube video, which I'm heavily relying on for the article.

Even though the Navigation site view in the Site Editor is the major enhancement in WP 6.3, there is no [field guide](https://make.wordpress.org/core/2023/07/18/wordpress-6-3-field-guide/) or dev notes about Navigation block. I am not aware of any comprehensive core blog posts about Navigation block since @getdave wrote during the 5.9 release. Therefore, I'm still digging into GitHub tickets from previous GB releases to learn and take notes. I am also keeping an eye on the other documention work in progress.

>Interesting I didn't know that. I can reprise a variant for the Learn WP video site if that helps?

That will definitely help. IMHO, I think a core blog post like [this one](https://make.wordpress.org/core/2022/01/07/the-new-navigation-block/) that Dave wrote for the 5.9 release is even better. I am hoping it's not too much to ask?

**Comment by tinjure20** [comment]
@bph, updates here. I have been working on a rough outline for the article (but not ready for sharing). Since there has been no core blog article on Navigation block since Dave's [this article](https://make.wordpress.org/core/2022/01/07/the-new-navigation-block/), I was contemplating including a section something like "**A brief retrospective**" where I wanted to highlight the major enhancements to the Nav block for the Site Editor from 6.0 to 6.3 release. I think this section might be helpful for people like me who find the Navigation block to be one of the most complex blocks.

It's taking me a while to go through the major enhancements from all GB releases since 5.9 and summarize them into a few paragraphs. In addition to the overall draft, I wanted Dave to look at this section for accuracy because he has been working on this feature since the beginning.

I am hoping to be able to share a more detailed article outline within the next few weeks.

**Comment by getdave** [comment]
I think a Make Blog post about changes to Navigation overall in WP is overdue. The issue is that I'm on vacation soon. Not writing dev notes was an oversight by Navigation contributors (myself included) really...

**Comment by tinjure20** [comment]
Dave, IMO a Make Blog post should never be late, even after your vacation.

**Comment by getdave** [comment]
I am writing one now along with other Navigation block contributors. Hopefully this will help?

**Comment by getdave** [comment]
The Make Blog post is available: [What’s new for Navigation in WordPress 6.2 and 6.3](https://make.wordpress.org/core/2023/08/23/whats-new-for-navigation-in-wordpress-6-2-and-6-3/)

**Comment by tinjure20** [comment]
>The Make Blog post is available: [What’s new for Navigation in WordPress 6.2 and 6.3](https://make.wordpress.org/core/2023/08/23/whats-new-for-navigation-in-wordpress-6-2-and-6-3/)

Dave, I greatly appreciate for the post. This will be incredibly helpful when preparing a brief tutorial for the Dev Blog. When a draft is ready, I intend to ask for your help in reviewing its technical accuracy.

**Comment by tinjure20** [comment]
> You are welcome and that is fine. Feel free to reach out.

Dave @getdave, I've finished writing the initial draft of the article now. I've DM'd you and shared a Google Doc link to request for a technical review from you.

**Comment by getdave** [comment]
@tinjure20 I have reviewed your draft. I think you could post the link to it here but keep "editing" lock to only reviewers.

I really appreciate all the hard work that's gone into the article. You clearly went to a lot of effort to research all the changes.

I've left some notes. Please excuse any brevity of my tone in the comments 🙇 

I would suggest considering the following:

- do you need to provide such a comprehensive review of past releases. Do you think it is sufficiently valuable to the reader to go into this level of detail? Is so then why?
- I felt the introduction was framed in a way that came across as negative about the features. Perhaps starting with a positive sentiment might help encourage readers to continue and also help to dispel the myth around the block being overly complex.

This is just my opinion and I welcome your thoughts on the above and in the document.

The article will need another review. I also think it would benefit from @bph's expert eye.

Thank you again for all the work here.

**Comment by tinjure20** [comment]
Dave @getdave, I appreciate you taking the time to review and leave your feedback, which I intend to go through carefully. I believe, your suggestions and comments will be immensely helpful improve the article.

The article is inspired by and based on your extensive YouTube tutorials and Make Blog posts (with Ben). I regret that I couldn't acknowledge the video tutorials due to the external link policy of Dev Blog.

**Comment by bph** [comment]
@getdave Thanks for your time reviewing this article and the ping 

@tinjure20 Ganesh, when you are ready, please share the Google Doc link and make it available for all who have a link to comment and suggest edits. I am looking forward to reading it.

**Comment by tinjure20** [comment]
@bph,  Below is the Google doc link of the article with @getdave's comments. I am currently working on Dave's edits, comments/suggestions. Maybe you could wait until I complete (within a day or two).
 
https://docs.google.com/document/d/1IGIGKFrcjTQDTyO4bpS02dEv7T27XuPLnUEDBrG-4lE/edit?usp=sharing

**Comment by bph** [comment]
Thanks @tinjure20 excellent. I'll wait until you are ready 👏

**Comment by tinjure20** [comment]
> I really appreciate all the hard work that's gone into the article. You clearly went to a lot of effort to research all the changes.

Your kind words touched me deeply and made me feel humbled. 

> I've left some notes. Please excuse any brevity of my tone in the comments 🙇

As I stated before [here](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1623883987), this piece is one of my learning projects. Whatever I was attempting to write in this article was doing so at the edge of my knowledge. These feedback greatly helped me improve my own comprehension of the topic and also the document. I was expecting a lot worse! 

> I felt the introduction was framed in a way that came across as negative about the features. Perhaps starting with a positive sentiment might help encourage readers to continue and also help to dispel the myth around the block being overly complex.

I fully agree, it's an oversight on my part. I have amended this section accordingly. Thank you.

> do you need to provide such a comprehensive review of past releases. Do you think it is sufficiently valuable to the reader to go into this level of detail? Is so then why?

A great question. IMO, this section helps connect the dots and adds educational value to the reader, who don't want to learn only what's in it but also how we arrived here. As suggested, I have updated the section with only a few bullet points and removed a few screenshots, as well.

Please allow me to explain why I went to such great lengths to work on this section and the reasoning behind including this section in the article.

- I have [expressed my frustration](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1653923475) at having no official field guides or comprehensive posts on this topic since the 5.9. The [recent Make WordPress post with 6.2 and 6.3](https://make.wordpress.org/core/2023/08/23/whats-new-for-navigation-in-wordpress-6-2-and-6-3/) was only added after the discussion on the issue [here](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1654079705). 
- Despite Dave's very instructive YouTube video tutorial, I was constrained from providing readers with links due to the [Dev Blog's policy](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1653457707) on external resource. To add some context and establish a connection between the evolution of a highly intricate feature of Navigation Block from 5.9 to its current state, I [believe](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1653994262), this section offers significant value to its readers, including myself and others with similar knowledge base.  
- I spent considerable time going through GitHub issues to learn how each release added enhancements to the current Navigation block (see my notes in the Google Doc). Many WordPress theme authors and small agency developers don't have such a luxury of time to dig into GitHub issues.
- I hope this conversation will stimulate discussions about writing a comprehensive official guides for each release to educate students and other curious learners.
- Now, I am leaving it to the Dev Blog team to decide if the section should be taken out or left as is. 

Finally, the article was inspired by and based on @getdave extensive YouTube tutorials (of which I am a big fan) and other Navigation block contributors. I picked up this topic due to my own knowledge gap as part of my "learn & share" project and not to take credit from the contributors. In my communication with @getdave, I requested that he co-author this article. It would be even better if he accepts to take over as author, which would add credibility to the article. I would be happy to stay in the props as a mention.

**Comment by tinjure20** [comment]
@bph , here is the link to the **updated** copy of the Google Doc draft article. 

https://docs.google.com/document/d/1LMhoxh7fN4xg372jtxDGfH8AzJWCs2TvjRyZ7_FYKMM/edit?usp=sharing

For transparency and ease of comparison, I have left @getdave  comments intact. The **original** Google Doc link with comments is [available here](https://github.com/WordPress/developer-blog-content/issues/149#issuecomment-1717283396).

**Comment by justintadlock** [comment]
I've went through this, mostly focusing on formatting issues. I still think it needs a more thorough copy-editing review. @marybaum or @abhansnuk, would either of you be available this week?

**Comment by marybaum** [comment]
I am! Probably Thursday, sooner if I can

**Comment by tinjure20** [comment]
@justintadlock, I appreciate your review of the draft article. Thank you.

**Comment by marybaum** [comment]
I'm in there now. I'll make little edits to grammar, English syntax and punctuation directly and bigger edits, that affect the tone, as suggestions. You'll see those as highlighted text that show a comment block on hover.

**Comment by tinjure20** [comment]
@getdave, thank you very much for twice reviewing (the original draft and the updated copy) for technical accuracy. You taught me a lot about the Navigation block through your extensive [YouTube videos](https://www.youtube.com/@DaveOnWP/search?query=Navigations) and Make WordPress articles. Without these excellent resources, I wouldn't have been able to learn about this topic and share my learning experience in this piece.

I am still waiting for the copy-editing review to be completed so that I can deal with all the feedbacks and comments in one go.

**Comment by tinjure20** [comment]
Thanks to Mary and Dave, I have updated their comments and feedbacks. @bph The copy-editing of the entire article draft is not yet complete.

**Comment by tinjure20** [comment]
Due to my other personal commitments, I would like to express my regret that I am unable to proceed the draft article to the finish line. I sincerely apologize to @bph, @justintadlock and all board members for letting down the trust placed in me. I respectfully request that the board reassign the topic to anyone who maybe interested to bringing this issue to the finish line. Any interested contributors could take over where I have left off and make their own.

I greatly appreciate all your help on this great ride and wish everyone a wonderful holiday season. Thank you.

**Comment by getdave** [comment]
> In my communication with @getdave, I requested that he co-author this article. It would be even better if he accepts to take over as author, which would add credibility to the article. I would be happy to stay in the props as a mention.

Apologies that I missed this. I would have to weigh this carefully as I have already committed myself to several responsibilities and features for the 6.5 release.

I could possibly look to move this forward if the Dev Blog team are willing to support.

Thanks for all your effort here @tinjure20. Your motivation is sound and I appreciate the level of research you've gone to and the obvious passion for making things better for folks who use WordPress.

**Comment by marybaum** [comment]
I’ll take a look in a few hours—for me it’s a Friday afternoon, and I have some bandwidth. Plus I already have some time in it—I think my edit took in about two-thirds of the total.

plus, the title, featured image and social copy are the parts of the process I’m fairly quick with 😜

**Comment by justintadlock** [comment]
I've got three days next week before going on break and can help push this live if we think we can do it in that timeframe.

I'm not sure who might be available beyond that with holiday schedules. But any of the Dev Blog admins feel free to carry it forward if you're available. Outside of that, we might have to publish in January.

**Comment by marybaum** [comment]
Edit done!

**Comment by bph** [comment]
I wrote an answer on the [thread in the Core-dev-blog channel](https://wordpress.slack.com/archives/C03RL47B3S8/p1702639892587939) and copy/paste it here as well: 

>Thank you @tinjure20. Sorry, it took so long to get your post over the finish line. I saw that @marybaum
 finished copy-editing,
The only suggestions I had was to remove screenshots that are not current anymore not to confuse users and to maybe add an example or two on how the navigation block is used in a template or pattern setting. When I get back from vacation, I will make those changes myself and work through the publish checklist, then we'll publish the article in your name as main author.

**Comment by tinjure20** [comment]
@bph , thank you. Let's @getdave  take care of this complex topic, and the Google Doc has editorial permission set up for him. I have posted a nearly identical note similar to this in a [thread in the dev-blog channel](https://wordpress.slack.com/archives/C03RL47B3S8/p1702728855475869?thread_ts=1702639892.587939&cid=C03RL47B3S8). 

@justintadlock , thank you, but since the genie is already out of the bottle, let Dave take care of the Doc. When this topic was proposed during the 6.3 development phase, there were no updated posts on the Make blog or Dev blog. I simply jumped in to fill my own knowledge-gap from Dave's extensive YouTube tutorials and share the experience, rather than seeking an authorship. Since we're already in the 6.5 development phase, the article needs to be updated with the new enhanced features from 6.4 and 6.5 dev cycles.

IMO, Dave is the right author to have written this article in the first place. I believe that Dev Blog readers would immensely benefit from Dave's expert perspective on this complex topic, rather than a novice learner's second-hand experience.

I regret for this timing, which was mainly due to the last Thursday Dev team meeting. Justin recently wrote, "WordPress doesn't anywhere", so let's have a great time with the family and loved ones during the holidays.

**Comment by justintadlock** [comment]
At this point, we're going to leave this open to anyone to pick up and update if they want to. Or, optionally, write a new draft that takes this in a different direction.

I'll remove the current assignees and relabel for the ticket needing a writer.

**Comment by tinjure20** [comment]
@justintadlock, Kindly request a new proposal. I plan to post this draft on my own website [tinjurewp.com](https://tinjurewp.com/) upon return from travel (around third week of Feb). Thank you @getdave, @justintadlock , @bph, @marybaum for comments, reviews and copy edits.

**Comment by bph** [comment]
It's probably best to close this issue and we can reopen if there is a need for a navigation block post on the Developer Blog or we just start a new discussion.
