### ISSUE TITLE
What you *can* and *cannot* do with PHP in patterns

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#214]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** January 25, 2024</sup>
A solid tutorial covering what functions are available to you when building patterns. For example, did you know that patterns are executed on `init`, a time when most WP conditionals are not yet set?

Why use PHP? Internationalization, dynamic URLs for loading media, and more.

You can also do things like loops instead of printing the block markup for repeated sections of the pattern with the same content (for example, a Columns block with the same nested columns).</div>

**Comment by justintadlock** [comment]
Drafting this here: https://docs.google.com/document/d/1TVSeEklV2StuUmwwIUu_1_SscQtc1XZ8jVMbltC05fM/edit?usp=sharing

**Comment by justintadlock** [comment]
Because we needed pretty much the same doc for the Theme Handbook, I ended up porting this as an article that will live under the upcoming Patterns chapter: https://docs.google.com/document/d/1b4K4w1GyW09Z-yJpwAODT3mPqQCDAG3H7Xr3kgqyWyg/edit?usp=sharing

I feel like that's the best place for this at this time. We can always build on top of that documentation with a Dev Blog article in the future. But I feel like I've accomplished what I set out to do (create a resource for themers to learn how to use PHP in patterns), so I'm closing this for now.

If anyone wants to pick it up with a new angle, we can always reopen.
