### ISSUE TITLE
Application state managed withDispatch, withSelect and compose 101

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#25]
This is  an article, that was used for testing the site and never made it into the editorial process. 
Here is the [public preview link ](https://developer.wordpress.org/news/?p=10&preview=1&_ppp=86d6639436)
It needs to be reviewed now.

**Comment by zzap** [comment]
I don't like that we have [a link to external blog](https://awhitepixel.com/blog/gutenberg-updating-withselect-and-withdispatch-into-react-hooks-useselect-and-usedispatch/) inside this article for a few reasons:

- there is no name of author (only the website name, A white pixel) - we have no idea who this person is
- there is a Code Merch section below this article - it is selling various products and leads to a completely different site 
- we don't want these articles to be used for promotional purpose, or do we?

I strongly suggest removing that link and using official React.js and WordPress documentation whenever possible. If it's not anywhere in documentation:
- open issue in [Docs repo](https://github.com/WordPress/Documentation-Issue-Tracker/issues) to be added in WordPress docs, or
- open issue in [Learning repo](https://github.com/WordPress/Learn/issues) to be added as lesson, or 
- open issue here to be added as a tutorial
- make note to add link to it into published article

**Comment by zzap** [comment]
Code examples need cleanup and better formatting.

I love that one of examples is from Jetpack. It promotes the way of learning by reading other people's code (which is made by, or approved by wp.org).

**Comment by zzap** [comment]
A typo in `withSelect` section:

```
You pass it a function which receives a select method.
```

**Comment by zzap** [comment]
I think this one needs rephrasing and maybe more detailed explanation. It feels like a slack message inside a company rather than explaining to a wide range of knowledge/experience levels of readers.

```
compose basically runs all of the methods given as a chain starting from the right, it’s a replacement of foo(bar(baz()))
```

Also, I would recommend avoiding foo/bar/baz vocabulary. It's too abstract and, sometimes, very unfriendly to junior developers.

**Comment by zzap** [comment]
`Comparing use and with methods` section needs more explanation. The differences in code examples are not obvious to people who are not that familiar with React. And people who are familiar enough, don't really need this explanation because they know it. 

Some questions to answer here:
- why with* example pass more props to `MyAwesomeComponent` than use* one?
- why is `const fooBar` differently positioned in with* and use* examples? If there's no reason for it then they should be in the same position. It's hard to notice important differences if non-important parts are different.
- why use* example doesn't have `compose`?

**Comment by dsas** [comment]
@zzap thank you for the feedback, all great points which I think I've addressed in the latest draft and will try to keep in mind for any future articles. I'd be grateful if you / @bph could give it another review.

FWIW this article originates from me (confident in PHP and jQuery era JS) getting up to speed with React+Gutenberg.

> I don't like that we have a link to external blog inside this article for a few reasons

All good reasons! I've removed that sentence, it's perhaps a bit premature to talk about converting between the two before even explaining what they are. 

> You pass it a function which receives a select method.

Unsure where the typo is here but I've reworded the sentence so perhaps it's gone. I subconsciously use en-gb spelling, though I think @bph and myself got them all earlier.

> Comparing use and with methods section needs more explanation.

I've reworked the code examples to include some inline comments and have expanded the surrounding paragraphs. Happy to work on this further if necessary.

**Comment by zzap** [comment]
>You pass it a function which receives a select method.

Oh so on first reading I thought it misses `pass it to a function` or `pass it as a function` or something like that. But it is:
` A function which receives a dispatch method is passed to withDispatch` or `withDispatch accepts a function as a parameter. This function receives a dispatch method`. Not a big deal, might be caused by English being my second language. 

I love the new `compose` explanation :heart: 

@dsas thank you so much for working on this. I know there was a lot of feedback and I'm probably a picky one, but I think it's much more understandable to wider audience and you made it possible. Thank you :heart:

**Comment by zzap** [comment]
@bph as far as I'm concerned it's good to go :raised_hands:

**Comment by dsas** [comment]
> Not a big deal, might be caused by English being my second language.

That gives you a very valuable perspective that I can't have! If writing can be made clearer for English-as-second-language people, then they'll be clearer for English-as-first..nth-language people too. A very large number of the readers will not have English as their first language, it's important for our writing to take that into account.

**Comment by bph** [comment]
Thank you, both @dsas and @zzap - it's published now: [Application state managed withDispatch, withSelect and compose 101](https://developer.wordpress.org/news/2022/12/13/application-state-managed-withdispatch-withselect-and-compose-101/)
